steps:
  - id: build-maven
    name: 'maven:3.6.3-jdk-11-slim'
    entrypoint: 'mvn'
    args: 
      - 'clean'
      - 'verify'

  - id: build-image-docker
    name: 'gcr.io/cloud-builders/docker'
    args: 
    - 'build'
    - '-t' 
    - 'gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA'
    - '-t'
    - 'gcr.io/$PROJECT_ID/$REPO_NAME:latest'
    - '.'

images:
- 'gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA'
- 'gcr.io/$PROJECT_ID/$REPO_NAME:latest'
