version: '3'

services:
  postgres:
    image: 'postgres:12.7-alpine'
    container_name: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker-compose-init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_SERVER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123

  app:
    build: .
    container_name: meli-challenge
    ports:
      - 8090:8090
    environment:
      - POSTGRES_SERVER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
    depends_on:
      - postgres

volumes:
  postgres-data: